[package]
name = "vrc-get-vpm"

# discreate versioning since this library will not have stable versions
version = "0.0.17-beta.0"

edition = "2024"

description = "Open Source client of VRChat Package Manager. This is the library is made for vrc-get."
readme = "README.md"
keywords = ["vpm", "package-manager"]
categories = ["command-line-utilities"]

[dependencies]
async-stream = "0.3"
async_zip = { version = "0.0.18", features = ["deflate", "tokio", "deflate64"] }
either = "1"
futures = "0.3"
hex = "0.4"
indexmap = "2"
itertools = "0.15"
log = { version = "0.4", features = ['kv'] }
pin-project-lite = "0.2"
reqwest = { version = "0.13", features = ["stream"], default-features = false, optional = true }
serde = "1"
serde_json = { version = "1", features = ["preserve_order"] }
sha2 = "0.11"
url = "2"
uuid = { version = "1", features = ["v4"] }
lazy_static = "1"
enum-map = "2"

tokio = { version = "1", features = ["fs", "process"] }
tokio-util = { version = "0.7" }

vrc-get-litedb = { version = "0.3.0-beta.8", optional = true, default-features = false, features = [
    'shared-mutex',
] }
serde_path_to_error = "0.1"
sha1 = "0.11"
tracing = "0.1.44"

[target."cfg(windows)".dependencies]
dirs-sys = "0.5"
winreg = { version = "0.56", optional = true }
windows = { version = "0.62", features = ["Win32_System_Threading", "Win32_Security"] }

[target."cfg(target_os = \"macos\")".dependencies]
plist = { version = "1", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[features]
default = ["rustls", "reqwest"]
reqwest = ["dep:reqwest"]
native-tls = ["reqwest/native-tls-vendored"]
rustls = ["reqwest/rustls"]

unity-hub = ["dep:plist", "windows/Win32_Storage_FileSystem"]
unity = []

experimental-project-management = ["vrc-get-litedb", 'unity-hub', 'unity']
experimental-unity-management = ["vrc-get-litedb", 'dep:winreg']

version-serde = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(r2cs)'] }

[workspace]
