name: Track Localization Changes

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    if: github.repository == 'vrc-get/vrc-get'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      discussions: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '20.x'
      - run: npm i --omit=dev
        working-directory: .github/scripts
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/localization-updates.js')
            await script({github, context})
